In [23]:
from platform import python_version
print(python_version())
import os
os.environ["KERAS_BACKEND"] = "theano"
import keras
import numpy as np


import ssl

ssl._create_default_https_context = ssl._create_unverified_context

3.7.3


In [24]:
(Train_data,Train_label), (Test_data,Test_label) = keras.datasets.cifar10.load_data()
Train_data = Train_data/255.0
Test_data = Test_data/255.0


In [25]:
print("Train data index 1: {} ".format(Train_data[0]))
print("Train label index 1: {}".format(Train_label[0]))
print("Test data index 2: {} ".format(Test_data[0]))
print("Test label index 1: {}".format(Test_label[0]))

Train data index 1: [[[0.23137255 0.24313725 0.24705882]
  [0.16862745 0.18039216 0.17647059]
  [0.19607843 0.18823529 0.16862745]
  ...
  [0.61960784 0.51764706 0.42352941]
  [0.59607843 0.49019608 0.4       ]
  [0.58039216 0.48627451 0.40392157]]

 [[0.0627451  0.07843137 0.07843137]
  [0.         0.         0.        ]
  [0.07058824 0.03137255 0.        ]
  ...
  [0.48235294 0.34509804 0.21568627]
  [0.46666667 0.3254902  0.19607843]
  [0.47843137 0.34117647 0.22352941]]

 [[0.09803922 0.09411765 0.08235294]
  [0.0627451  0.02745098 0.        ]
  [0.19215686 0.10588235 0.03137255]
  ...
  [0.4627451  0.32941176 0.19607843]
  [0.47058824 0.32941176 0.19607843]
  [0.42745098 0.28627451 0.16470588]]

 ...

 [[0.81568627 0.66666667 0.37647059]
  [0.78823529 0.6        0.13333333]
  [0.77647059 0.63137255 0.10196078]
  ...
  [0.62745098 0.52156863 0.2745098 ]
  [0.21960784 0.12156863 0.02745098]
  [0.20784314 0.13333333 0.07843137]]

 [[0.70588235 0.54509804 0.37647059]
  [0.67843137 0.4

In [26]:
print("Train data shape: {}".format(Train_data.shape))
print("Train label shape: {}".format(Train_label.shape))
print("Test data shape: {}".format(Test_data.shape))
print("Test label shape: {}".format(Test_label.shape))

Train data shape: (50000, 32, 32, 3)
Train label shape: (50000, 1)
Test data shape: (10000, 32, 32, 3)
Test label shape: (10000, 1)


In [27]:
Train_label = keras.utils.to_categorical(Train_label, 10)
Test_label = keras.utils.to_categorical(Test_label, 10)

In [28]:
print("Train label shape: {}".format(Train_label.shape))
print("Test label shape: {}".format(Test_label.shape))

Train label shape: (50000, 10)
Test label shape: (10000, 10)


In [35]:
model = keras.models.Sequential([
    keras.layers.Conv2D(32,(3,3), padding="same", input_shape=(32,32,3), activation="relu"),
    keras.layers.Conv2D(32,(3,3)),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Dropout(0.2),
    keras.layers.Conv2D(32,(3,3), padding="same"),
    keras.layers.Conv2D(32,(3,3)),
    keras.layers.MaxPooling2D(pool_size=(2,2)),
    keras.layers.Dropout(0.2),
    keras.layers.Flatten(),
    keras.layers.Dense(500, activation="relu"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation="softmax")
])

In [36]:
model.compile(optimizer="adam", metrics=["accuracy"], loss="categorical_crossentropy")

In [37]:
model.fit(Train_data,Train_label, epochs=10,batch_size=32)

Epoch 1/10
50000/50000 [==============================] - 354s 7ms/step - loss: 1.3897 - accuracy: 0.5012
Epoch 2/10
50000/50000 [==============================] - 335s 7ms/step - loss: 1.0333 - accuracy: 0.6385
Epoch 3/10
50000/50000 [==============================] - 342s 7ms/step - loss: 0.8838 - accuracy: 0.6936
Epoch 4/10
50000/50000 [==============================] - 349s 7ms/step - loss: 0.7885 - accuracy: 0.7282
Epoch 5/10
50000/50000 [==============================] - 360s 7ms/step - loss: 0.7224 - accuracy: 0.7502
Epoch 6/10
50000/50000 [==============================] - 351s 7ms/step - loss: 0.6743 - accuracy: 0.76730s - loss: 0.6743 - accuracy: 
Epoch 7/10
50000/50000 [==============================] - 362s 7ms/step - loss: 0.6170 - accuracy: 0.7856
Epoch 8/10
50000/50000 [==============================] - 322s 6ms/step - loss: 0.5854 - accuracy: 0.7975
Epoch 9/10
50000/50000 [==============================] - 308s 6ms/step - loss: 0.5522 - accuracy: 0.8069
Epoch 10/10
5000

In [44]:
classes=["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]
prediction = model.predict(Test_data)
print("actual: {}".format(classes[np.argmax(Test_label[0])]))
print("predicted: {}".format(np.argmax(prediction[0])))

actual: cat
predicted: 3
