In [105]:
from platform import python_version
print(python_version())
import os
os.environ["KERAS_BACKEND"] = "theano"
import keras
import numpy as np


import ssl

ssl._create_default_https_context = ssl._create_unverified_context

3.7.3


In [106]:
(Train_data, Train_label) , (Test_data, Test_label) = keras.datasets.reuters.load_data()

In [107]:
word_to_index = keras.datasets.reuters.get_word_index()

In [108]:
word_to_index['deal']

602

In [109]:
index_to_word = {}
for key, value in word_to_index.items():
    index_to_word[value] = key

In [113]:
index_to_word[10000]
classes = max(Train_label) + 1
class_names = ['cocoa','grain','veg-oil','earn','acq','wheat','copper','housing','money-supply',
   'coffee','sugar','trade','reserves','ship','cotton','carcass','crude','nat-gas',
   'cpi','money-fx','interest','gnp','meal-feed','alum','oilseed','gold','tin',
   'strategic-metal','livestock','retail','ipi','iron-steel','rubber','heat','jobs',
   'lei','bop','zinc','orange','pet-chem','dlr','gas','silver','wpi','hog','lead']
print(' '.join(index_to_word[x] for x in Test_data[0]))

print("label: {}".format (class_names[Test_label[0]]))


the in wants intermediate 3 how types could mln at against 2 guidelines vs end products opec he will will along results and willingly exports 3 purchased each it stubbornly profit 3 avondale profit agreement in around corp should for 3 cannot mln in ended said avondale a 54 but 3 stubbornly a only generally political primarily date other under well a in british rate gain if demand at an div its taking report montreal systems were is and production had vs 000 7 issued year for 0 a in buffer rate loss may results tariffs dlrs is and from 39 s 000 for 3 cannot pre 50 east that in foods products opec last 1 fall change 1 approval in 15 2 said in opec 28 but for 3 cannot cts systems which is half be 6 iffezheim uobm said president amount pct dlrs
label: earn


In [114]:
tokenizer = keras.preprocessing.text.Tokenizer(num_words=1000)
Train_data = tokenizer.sequences_to_matrix(Train_data,mode="binary")
Test_data = tokenizer.sequences_to_matrix(Test_data,mode="binary")
Train_label = keras.utils.to_categorical(Train_label, classes)
Test_label = keras.utils.to_categorical(Test_label, classes)

In [115]:
print("Train data : {}".format(Train_data))
print("Train data shape :{}".format(Train_data.shape))
print("Train labels : {}".format(Train_label))
print("Train labels shape :{}".format(Train_label.shape))
print("Test data : {}".format(Test_data))
print("Test data shape :{}".format(Test_data.shape))
print("Test labels : {}".format(Test_label))
print("Test data shape :{}".format(Test_label.shape))


Train data : [[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
Train data shape :(8982, 1000)
Train labels : [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Train labels shape :(8982, 46)
Test data : [[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
Test data shape :(2246, 1000)
Test labels : [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Test data shape :(2246, 46)


In [116]:
model = keras.models.Sequential([
    keras.layers.Dense(500,input_shape=(1000,),activation="relu"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(250, activation="relu"),
    keras.layers.Dense(classes, activation="softmax")
])

In [117]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['accuracy'])


In [118]:
model.fit(Train_data, Train_label, epochs=10,batch_size=32)

Epoch 1/10
8982/8982 [==============================] - 3s 345us/step - loss: 1.3063 - accuracy: 0.7031
Epoch 2/10
8982/8982 [==============================] - 3s 347us/step - loss: 0.6831 - accuracy: 0.8327
Epoch 3/10
8982/8982 [==============================] - 3s 380us/step - loss: 0.4314 - accuracy: 0.8922
Epoch 4/10
8982/8982 [==============================] - 4s 391us/step - loss: 0.3070 - accuracy: 0.9226
Epoch 5/10
8982/8982 [==============================] - 4s 442us/step - loss: 0.2405 - accuracy: 0.9391
Epoch 6/10
8982/8982 [==============================] - 4s 424us/step - loss: 0.2131 - accuracy: 0.9453
Epoch 7/10
8982/8982 [==============================] - 4s 412us/step - loss: 0.1890 - accuracy: 0.9475
Epoch 8/10
8982/8982 [==============================] - 4s 436us/step - loss: 0.1731 - accuracy: 0.9487
Epoch 9/10
8982/8982 [==============================] - 4s 489us/step - loss: 0.1688 - accuracy: 0.9506
Epoch 10/10
8982/8982 [==============================] - 4s 420u

In [120]:
prediction = model.predict(Test_data)

In [123]:
print(class_names[np.argmax(prediction[0])])

earn
